### ISSUE TITLE
Shouldn't the token be verified in each request?

### ISSUE THREAD

**Issue by andrefs** [brentertz/redux-auth-demo#2]
Hey there, I just tried to set "token" to "foo" in my Local Storage using the Chrome dev tools.

I gained access to the /account page, because you're not checking the validity of the "token", just checking if it is there...

**Comment by brentertz** [comment]
Hi Andre,

You can hack your way to navigate the client side route, but it will not display any protected data, as all API calls are protected and will fail with a `401: unauthorized` without a valid token.

You'll also want to note that navigating via the UI and client side router does not actually issue a request.  Depending on your applications needs, you might need to add an extra bit to validate the token for certain client side actions.

-Brent

**Comment by andrefs** [comment]
Hi Brent,

You're absolutely right, my bad.
Thank you for answering and also thank you for taking the time to put together this demo and share it online.

Best

andré
